name: Deploy Application

on:
  push:
    branches: [main]

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and Javascript
        run: |
          npm install
          npm run prod

      - name: Configure PHP 7.4
        run: |
          sudo add-apt-repository ppa:ondrej/php
          sudo apt-get update
          sudo apt-get install -y php7.4-cli php7.4-fpm php7.4-mysql php7.4-pgsql php7.4-sqlite3 php7.4-curl php7.4-gd php7.4-intl php7.4-mbstring php7.4-xml php7.4-zip

      - name: Composer install
        run: |
          composer install --no-dev --prefer-dist --no-progress --no-suggest --no-interaction
